  
stages:
  - stage: "Build"
    displayName: "Run any steps required before building the apps"
    jobs:
      - job: "Build"
        displayName: "Build actions"

        steps:
          - template: ../buildActionTemp.yml